export const elements = {
    'header': document.querySelector('.header'),
    'inputField': document.querySelector('.header__addToDo'),
    'inputTextField': document.querySelector('.header__toDoText'),
    'hiddenDueDateInput': document.querySelector('.header__dueDate'),
    'dueDateDisplay': document.querySelector('.header__showCalendar-text'),
    'instruction': document.querySelector('.instruction'),
    'instructionBtn': document.querySelector('.instruction__toggle'),
    'instructionText': document.querySelector('.instruction__toggle-text'),
    'toDoListSection': document.querySelector('.toDoList'),
    'toDoList': document.querySelector('.toDoList__full'),
    'completedListSection': document.querySelector('.completedList'),
    'completedList': document.querySelector('.completedList__full')
};

export const domStrings = {
    'instructionText': '.instruction__text-wrapper',
    'instructionIcon': '.instruction__toggle-icon',
    'toDoListItem': '.toDoListItem',
    'toDoListItemText': '.toDoListItem__edit-wrapper',
    'toDoListItemTextEdit': '.toDoListItem__edit-popup',
    'toDoLisItemTextEditForm': '.toDoListItem__edit-form',
    'toDoLisItemTextEditInput': '.toDoListItem__edit-text',
    'toDoListItemTextEditCancel': '.toDoListItem__edit-cancel',
    'toDoListItemDueDate': '.toDoListItem__dueDate-wrapper',
    'toDoListItemDueDateEdit': '.toDoListItem__dueDate-edit-popup',
    'toDoLisItemTextDueDateEditForm': '.toDoListItem__dueDate-edit-form',
    'toDoLisItemTextDueDateInput': '.toDoListItem__dueDate-edit',
    'toDoListItemTextDueDateEditCancel': '.toDoListItem__dueDate-edit-cancel',
    'toDoListCompleteBtn': '.toDoListItem__complete-btn',
    'toDoListPaginationDiv': '.toDoList__pagination',
    'toDoListBackBtn': '.toDoList__pagination-btn--backward',
    'toDoListForwardBtn': '.toDoList__pagination-btn--forward',
    'toDoListPage': '.toDoList__pagination-page-number',
    'completedListItem': '.completedListItem',
    'completedListItemRedoBtn': '.completedListItem__redo-btn',
    'completedListItemDeleteBtn': '.completedListItem__delete-btn',
    'completedListPaginationDiv': '.completedList__pagination',
    'completedListBackBtn': '.completedList__pagination-btn--backward',
    'completedListForwardBtn': '.completedList__pagination-btn--forward',
    'completedListPage': '.completedList__pagination-page-number',
    'sortSelectionToDoListDiv': '.toDoList__sort-selection-wrapper',
    'sortSelectionToDoList': '.toDoList__sort-selection',
    'sortSelectionCompletedListDiv': '.completedList__sort-selection-wrapper',
    'sortSelectionCompletedList': '.completedList__sort-selection',
    'resetBtn': '.btn-reset-all'
};